# Generated by Django 5.0.6 on 2024-07-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinematography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('movie', 'Movie'), ('series', 'Series'), ('cartoons', 'Cartoons'), ('anime', 'Anime')], max_length=10)),
                ('genre', models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('fantasy', 'Fantasy'), ('horror', 'Horror'), ('romance', 'Romance'), ('sci-fi', 'Sci-fi')], max_length=10)),
                ('description', models.TextField()),
            ],
        ),
    ]
