# Generated by Django 5.0.6 on 2024-07-07 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinematography',
            name='release_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='cinematography',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
