# Generated by Django 5.0.6 on 2024-07-07 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
