# Generated by Django 5.0.6 on 2024-07-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinematography',
            name='category',
            field=models.CharField(choices=[('none', 'None'), ('movie', 'Movie'), ('series', 'Series'), ('cartoons', 'Cartoons'), ('anime', 'Anime')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cinematography',
            name='genre',
            field=models.CharField(choices=[('none', 'None'), ('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('fantasy', 'Fantasy'), ('horror', 'Horror'), ('romance', 'Romance'), ('sci-fi', 'Sci-fi')], max_length=10),
        ),
    ]
