# Generated by Django 5.0.6 on 2024-07-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0008_alter_cinematography_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_images/1.jpg', upload_to='profile_images'),
        ),
    ]
