# Generated by Django 5.0.6 on 2024-07-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0011_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first',
            field=models.ImageField(default='', upload_to='media/profile_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='forth',
            field=models.ImageField(default='', upload_to='media/profile_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_images/1.png', upload_to='media/profile_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='second',
            field=models.ImageField(default='', upload_to='media/profile_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='third',
            field=models.ImageField(default='', upload_to='media/profile_images'),
        ),
    ]
