# Generated by Django 5.0.6 on 2024-07-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0014_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinematography',
            name='poster_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
