# Generated by Django 5.0.6 on 2024-07-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0015_cinematography_poster_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinematography',
            name='poster_path',
        ),
        migrations.AlterField(
            model_name='cinematography',
            name='category',
            field=models.CharField(choices=[('movie', 'Movie'), ('series', 'Series'), ('cartoons', 'Cartoons'), ('anime', 'Anime')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cinematography',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('fantasy', 'Fantasy'), ('horror', 'Horror'), ('romance', 'Romance'), ('sci-fi', 'Sci-fi')], max_length=10),
        ),
    ]
