# Generated by Django 5.0.6 on 2024-07-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0016_remove_cinematography_poster_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinematography',
            name='poster_path',
            field=models.CharField(default='default_poster.jpg', max_length=255),
        ),
    ]
